# syntax=docker/dockerfile:1

FROM python:3.9-alpine

RUN mkdir -p /home/app
RUN addgroup -S app && adduser -S app -G app
ENV HOME=/home/app
WORKDIR $HOME

RUN apk update && apk add curl
COPY ./requirements.bot.txt /home/app/requirements.txt
USER app
RUN pip install --upgrade pip
RUN pip install -r /home/app/requirements.txt

COPY --chown=app . yt-podcast-bot
WORKDIR $HOME/yt-podcast-bot

CMD ["python", "/home/app/yt-podcast-bot/bot.py"]